version: '3.8'

services:
  php:
    build: .
    container_name: my_php_app1
    volumes:
      - ./VipassanaWebsiteBasic:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-server1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: vipassana
      MYSQL_USER: vipassana_user
      MYSQL_PASSWORD: vipassana_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-server1
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-server1
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql

volumes:
  mysql_data:
